# Generated by Django 6.0.2 on 2026-02-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('gp_name', models.CharField(max_length=120)),
                ('circuit_name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('session_type', models.CharField(max_length=5)),
                ('circuit_type', models.CharField(max_length=20)),
                ('is_simulated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('speed', models.IntegerField(default=0)),
                ('racing', models.IntegerField(default=0)),
                ('reaction', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('consistency', models.IntegerField(default=0)),
                ('error_rate', models.IntegerField(default=0)),
                ('street_affinity', models.IntegerField(default=0)),
                ('high_speed_affinity', models.IntegerField(default=0)),
                ('wet_affinity', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('pole_positions', models.IntegerField(default=0)),
                ('fastest_laps', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='f1.team')),
            ],
        ),
        migrations.CreateModel(
            name='SessionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('points_gained', models.IntegerField(default=0)),
                ('stats_gained', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='f1.seasonsession')),
            ],
            options={
                'unique_together': {('session', 'driver')},
            },
        ),
    ]
