# Generated by Django 6.0.2 on 2026-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='image_key',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
